#!/bin/bash
core_id=(824 825 826 827 864 865 866 867 8a4 8a5 8a6 8a7 8e4 8e5 8e6 8e7)
i=0
for elf in $@; do
    # echo $elf
    e-objcopy --srec-forceS3 --output-target srec --coreid \
        "${core_id[i]}" "$elf" "$elf".srec
    # echo ${core_id[i]}
    let i++
    true # to surpass error status on only one core
done
